language: cpp

compiler: gcc

before_install: 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -qq libcppunit-dev
- export CXX="g++-4.8"

before_script:
- ./install-pugixml.sh
- ./install-sdl2.sh
- ./install-sdl_ttf.sh
- PATH=$PATH:/usr/local/lib

script:
- cd tests
- echo $PATH
- $CXX --version
- make test
- ./sdl_gui
