language: cpp

compiler: gcc

before_install: 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse"
- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe multiverse"
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -qq libcppunit-dev
- sudo apt-get install -qq libsdl2-dev
- sudo apt-get install -qq libsdl2-ttf-dev
- export CXX="g++-4.8"

before_script:
- ./install-pugixml.sh

script:
- cd
- cd tests
- $CXX --version
- make test
- ./sdl_gui
