language: cpp

compiler: gcc

before_install: 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -qq libcppunit-dev
- export CXX="g++-4.8"
- ./install-pugixml.sh
- ./install-sdl2.sh
- ./install-sdl_ttf.sh
- export PATH=$PATH:/usr/local/lib
- ls /usr/local/lib/ | grep "SDL"
- sudo ldconfig

script:
- cd tests
- echo $PATH
- $CXX --version
- make test
- ./sdl_gui
