language: cpp

compiler: gcc

before_install: 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo pip install cpp-coveralls

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -qq libcppunit-dev
- export CXX="g++-4.8"
- ./install-pugixml.sh
- ./install-sdl2.sh
- ./install-sdl_ttf.sh 
- sudo ldconfig

script:
- cd tests
- $CXX --version
- make test
- ./sdl_gui

after_success:
- coveralls --exclude lib --exclude tests --gcov-options --relative-only
