language: cpp

compiler: gcc

before_install: 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo pip install cpp-coveralls

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -qq libcppunit-dev
- export CXX="g++-4.8"
- gcov --version
- sudo ln -fs /usr/bin/gcov-4.8 /usr/bin/gcov
- gcov --version
- ./install-pugixml.sh
- ./install-sdl2.sh
- ./install-sdl_ttf.sh 
- sudo ldconfig

script:
- cd tests
- $CXX --version
- make test
- ./sdl_gui

after_success:
- cd ..
- coveralls --exclude tests --gcov-options '\-r' -b ./src
